# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.3.12
FROM docker.io/library/ruby:$RUBY_VERSION

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential curl git libvips libyaml-dev libpq-dev pkg-config \
      postgresql-client shared-mime-info && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle" \
    RAILS_ENV="development"

COPY Gemfile Gemfile.lock ./
RUN bundle install || true

COPY . .

EXPOSE 3000
CMD ["./bin/dev"]
